#!/usr/bin/env bash
# Claude PreToolUse hook — Write|Edit
# Block direct edits to uv.lock — it must only be regenerated by uv/just commands.
#
# uv.lock is a machine-generated lockfile. Manual edits corrupt the hash
# integrity and break reproducible installs. The only correct ways to change it:
#
#   uv lock            — regenerate from pyproject.toml constraints
#   uv lock --upgrade  — upgrade all packages
#   just update        — upgrade + sync (the recommended recipe)
#   just sync          — install from the current lockfile
#
# This applies to both the template repo's lockfile and any generated project's
# lockfile. CLAUDE.md explicitly states: "uv.lock — Never hand-edit."
#
# Reference : Custom — project-specific hook, not derived from ECC.
#             Enforces the uv.lock rule documented in CLAUDE.md.
# Exits     : 0 = allow  |  2 = block

set -uo pipefail

INPUT=$(cat)

FILE_PATH=$(python3 - <<'PYEOF'
import json, sys

data = json.loads(sys.stdin.read())
print(data.get("tool_input", {}).get("file_path", ""))
PYEOF
<<<"$INPUT") || { echo "$INPUT"; exit 0; }

BASENAME=$(basename "$FILE_PATH")

if [[ "$BASENAME" == "uv.lock" ]]; then
    echo "┌─ BLOCKED: Direct edit to uv.lock" >&2
    echo "│" >&2
    echo "│  uv.lock is machine-generated and must never be hand-edited." >&2
    echo "│  Manual edits break hash integrity and reproducible installs." >&2
    echo "│" >&2
    echo "│  To update the lockfile:" >&2
    echo "│    just update          — upgrade all packages + sync" >&2
    echo "│    uv lock              — regenerate from pyproject.toml" >&2
    echo "│    uv lock --upgrade    — upgrade all packages" >&2
    echo "│    uv add <package>     — add a dependency (updates lockfile)" >&2
    echo "└─" >&2
    exit 2
fi

echo "$INPUT"
