# .github/labeler.yml
# actions/labeler@v6
# https://github.com/actions/labeler

template:
  - changed-files:
    - any-glob-to-any-file: 'template/**/*'

tests:
  - changed-files:
    - any-glob-to-any-file: 'tests/**/*'

ci:
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'

copier:
  - changed-files:
    - any-glob-to-any-file: 'copier.yml'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'pyproject.toml'
      - 'uv.lock'

documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'

scripts:
  - changed-files:
    - any-glob-to-any-file: 'scripts/**/*'

build:
  - changed-files:
    - any-glob-to-any-file: 'justfile'
